kafka:
  consumer-group: kafka-poc-group-1
  topic-poc-kafka-1: kafka-poc-topic-1
  topic-poc-kafka-2: kafka-poc-topic-2

secerts:
  kafka-address: ["localhost:9092"]
  elastic-address: http://localhost:9200
  redis-address: ""

